<a id="intro"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            1. Introduction:
            </span>   
        </font>    
</h2>

<h3 >   
      <font color = black >
            <span style='font-family:Georgia'>
            Introduction:
            </span>   
        </font>    
</h3>
<p>
    <span style='font-family:Georgia'>
    This project aims to leverage machine learning to accurately estimate the price of a car based on its features such as brand, model, engine size, mileage, and other relevant attributes. By building predictive models, this project helps consumers, car dealerships, and businesses make data-driven decisions on car valuations.
    </span>
</p>   
<hr>
<h3>
    <font color = black >
        <span style='font-family:Georgia'>
            Business Understanding:
            </span>   
        </font>    
</h3>
<p>
    <span style='font-family:Georgia'>
Car prices fluctuate due to various factors such as brand, age, condition, mileage, fuel type, and market demand. Accurate price prediction is essential for stakeholders like:

<li><b>Consumers:</b> Looking for fair market prices when buying or selling vehicles.</li>
<li><b>Dealerships:</b> Setting competitive prices while maintaining profitability.</li>
<li><b>Insurance Companies:</b> Assessing accurate car values for coverage plans.</li>
    </span>
    </p>
<u1>
    In a competitive and data-rich market, leveraging machine learning models helps predict the value of used cars and streamlines pricing strategies.
</u1>

<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            Business Objective:
            </span>   
        </font>    
</h3>
<p>
    <span style='font-family:Georgia'>
The primary objective is to develop a machine learning model that accurately predicts car prices based on the features provided. The model should:

<li>Assist in predicting car prices for both buyers and sellers.</li>
<li>Help businesses optimize pricing strategies, improving sales and customer satisfaction.</li>
<li>Improve decision-making processes regarding insurance valuations and loan approvals.</li>
    </span>
</p>
<u1>
By delivering an accurate prediction system, the project aims to reduce human biases, improve pricing transparency, and increase profitability for businesses.
</u1>

<a id="libraries"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            2. Getting Jupyter Ready:
            </span>   
        </font>    
</h2>

<h3 name='libraries'>   
      <font color = black >
            <span style='font-family:Georgia'>
            2.1 Import Python Libraries:
            </span>   
        </font>    
</h3>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

<a id="import"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            3. Reading & Understanding the data
            </span>   
        </font>    
</h2>

<a id="input"></a>
<h3 name='libraries'>   
      <font color = black >
            <span style='font-family:Georgia'>
            3.1 Importing the input files
            </span>   
        </font>    
</h3>

In [ ]:
car=pd.read_csv('quikr_car.csv')

In [ ]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [ ]:
car.shape

(892, 6)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

<a id="inspect"></a>
<h3 name='libraries'>   
      <font color = black >
            <span style='font-family:Georgia'>
            3.2 Inspect the columns
            </span>   
        </font>    
</h3>

In [ ]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [ ]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [ ]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [ ]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

The columns have certain quality issues

- year has many non year values
- year object to int
- price has 'Ask for Price'
- price object to int
- kms driven has kms with integers
- kms object to int
- kms has nan values
- fuel type has nan values
- keep first 3 words of name

<a id="clean"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            4. Data Cleaning & Manipulation
            </span>   
        </font>    
</h2>

<a id="null"></a>
<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            4.1 Checking of object type
            </span>   
        </font>    
</h3>

In [ ]:
car['year'].str.isnumeric()

0       True
1       True
2       True
3       True
4       True
       ...
887    False
888     True
889     True
890     True
891     True
Name: year, Length: 892, dtype: bool

In [ ]:
car=car[car['year'].str.isnumeric()]

In [ ]:
car.shape

(842, 6)

In [ ]:
car['year']=car['year'].apply(int)

<ipython-input-14-a26124290129>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['year']=car['year'].apply(int)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB

In [ ]:
car=car[car['Price']!='Ask For Price']

In [ ]:
car['Price']=car['Price'].str.replace(',','').apply(int)

<ipython-input-17-57f656385388>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['Price']=car['Price'].str.replace(',','').apply(int)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [ ]:
car['kms_driven']=car['kms_driven'].str.split().str[0].str.replace(',','')

<ipython-input-19-1847c8b1233f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['kms_driven']=car['kms_driven'].str.split().str[0].str.replace(',','')

In [ ]:
car=car[car['kms_driven'].str.isnumeric()]

In [ ]:
car['kms_driven']=car['kms_driven'].astype(int)

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

<a id="null"></a>
<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            4.2 Checking of null values
            </span>   
        </font>    
</h3>

In [ ]:
car[car['fuel_type'].isnull()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [ ]:
car=car.drop(132,axis=0)

In [ ]:
car[car['fuel_type'].isnull()]

Empty DataFrame
Columns: [name, company, year, Price, kms_driven, fuel_type]
Index: []

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [ ]:
car['name']=car['name'].str.split().str[0:3].str.join(' ')

In [ ]:
car.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [ ]:
car=car.reset_index().drop('index',axis=1)

In [ ]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [ ]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

<a id="null"></a>
<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            4.3 Checking for outliers
            </span>   
        </font>    
</h3>

In [ ]:
car[car['Price']>6e6]

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [ ]:
#sns.scatterplot(data=car,x='name',y='Price')
#plt.xticks(rotation=90);

In [ ]:
car=car[car['Price']<6e6]

In [ ]:
car.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [ ]:
car=car.reset_index(drop=True)

In [ ]:
car.to_csv('cleaned_car.csv')

<a id="clean"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            5. Fitting the model
            </span>   
        </font>    
</h2>

<a id="null"></a>
<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            5.1 Train-Test split
            </span>   
        </font>    
</h3>

In [ ]:
X=car.drop('Price',axis=1)

In [ ]:
y=car['Price']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

<a id="null"></a>
<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            5.2 One-hot encoding of categorical variables
            </span>   
        </font>    
</h3>

In [ ]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [ ]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [ ]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

<a id="null"></a>
<h3>   
      <font color = black >
            <span style='font-family:Georgia'>
            5.3 Fitting of the model
            </span>   
        </font>    
</h3>

In [ ]:
lr=LinearRegression()

In [ ]:
pipe=make_pipeline(column_trans,lr)

In [ ]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

<a id="clean"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            6. Making predictions
            </span>   
        </font>    
</h2>

In [ ]:
y_pred=pipe.predict(X_test)

In [ ]:
r2_score(y_test,y_pred)

0.6792832138866173

In [ ]:
for i in range(10):
  X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
  lr=LinearRegression()
  pipe=make_pipeline(column_trans,lr)
  pipe.fit(X_train,y_train)
  y_pred=pipe.predict(X_test)
  print(r2_score(y_test,y_pred),i)

0.6896830536384548 0
0.6256374280501509 1
0.7328307064610267 2
0.6219209267943058 3
0.7056957001954487 4
0.5394145461390325 5
0.5010977416831943 6
0.6098139096075159 7
0.6515670473903173 8
0.6155868232322789 9

In [ ]:
scores=[]
for i in range(1000):
  X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
  lr=LinearRegression()
  pipe=make_pipeline(column_trans,lr)
  pipe.fit(X_train,y_train)
  y_pred=pipe.predict(X_test)
  scores.append(r2_score(y_test,y_pred))

In [ ]:
np.argmax(scores)

4

In [ ]:
scores[np.argmax(scores)]

0.8456515104452564

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8456515104452564

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [ ]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([459113.49353657])

<a id="conclusion"></a>
<h2>   
      <font color = purple >
            <span style='font-family:Georgia'>
            7. Conclusions
            </span>   
        </font>    
</h2>

<p>
    <span style='font-family:Georgia'>
The Car Price Prediction project successfully demonstrates the power of machine learning in accurately estimating car prices based on various features such as brand, model, engine size, mileage, and more. By building and optimizing predictive models, we can provide a reliable tool for consumers, dealerships, and businesses to make informed decisions regarding car valuations. This not only improves transparency in the pricing process but also helps businesses optimize their pricing strategies, leading to increased customer satisfaction and profitability.
        </p>
    <p>
Furthermore, the model's scalability allows for future integration of additional features and real-time data, making it a valuable asset for various industries like car sales, insurance, and financial services. The successful deployment of such models can significantly reduce pricing discrepancies and create a more efficient marketplace for used vehicles
    </span>
</p>